name: semantic-release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release with tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx -p util -p dateformat -p fs -p semantic-release-gitmoji -p @semantic-release/git -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/changelog semantic-release
